services:
  - type: web
    name: dlsc
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1